### ISSUE TITLE
[FE] add react-i18next

### ISSUE THREAD

**Issue by BelousSofiya** [BelousSofiya/medsite#22]

**Comment by leotarditi** [comment]
Hello BelousSofiya,

My name is Leo, and I am a front-end developer with experience in React and Next.js. I’ve been looking for opportunities to contribute to open-source projects and gain more experience.

I noticed you’re looking to add support for react-i18next, and I would love to help with that. I’ve worked with this library in other projects and know about implementing internationalization (i18n).

If you'd like, I can start by reviewing the current project structure and proposing a plan to integrate react-i18next efficiently. I can also assist with the initial setup and help translate some content into Spanish if needed.

I'm looking forward to contributing!

**Comment by BelousSofiya** [comment]
Hi, Leo.
I am very happy about your unexpected offer. I will not refuse help and advice. And adding Spanish to the project languages ​​- that would be great. However, I have to warn you that this repository is just my pet project, not a big open source project. I have little free time and therefore the work is progressing slowly. If you are okay with this, please write to me.

P.S. How did you even find this little repository?
